// src/app/about-me/about-me.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: '.about-me.content',
  templateUrl: './about-me.component.html',
  styleUrls: ['./about-me.component.less']
})
export class AboutMeComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="title">
  <h2>about me</h2>
</div>
<div class="body-copy">
  <p>After years spent working in London and Melbourne in jobs that often left me
    feeling frazzled and unable to sleep, and turning to reflexology in my first pregnancy -
    I was overwhelmed by the effect it had on me.  I felt able to sleep much more deeply than
    I had in ages.  It affected me so much that I hatched a plan.  I started studying and
    practicing after I had my second baby, qualified with a Level 3 Diploma in Reflexology
    from Brighton Holistics and became a member of the Federation of Holistic Therapists and
    Association of Reflexologists. I have also become a member of the Complementary &amp;
    Natural Healthcare Council (CNHC) which means that if you have a private healthcare plan,
    you should be able to claim for the cost of the treatment.</p>
  <p>I live in Horsham with my two young boys and fur baby. These guys have taught me the importance of self-care - you can’t pour from an empty cup!  I am married to an Aussie, and we are normally planning our next big (or little) trip.  I love a festival, beach, music, yoga and running. Being in nature makes me happy.</p>
  <p style="margin-top: 50px; text-align: center;">
    <img src="assets/images/em-sig.png" />
  </p>
</div>
<div class="images">
  <img src="assets/images/excellence-in-reflexology-logo.png" />
  <img src="assets/images/fht_psa_logo_member.jpg" />
</div>
<div class="image"></div>

// src/views/about-me.vue
<template>
  <div class="about-me content">
    <div class="title">
      <h2>about me</h2>
    </div>
    <div class="body-copy">
      <p>After years spent working in London and Melbourne in jobs that often left me
        feeling frazzled and unable to sleep, and turning to reflexology in my first pregnancy -
        I was overwhelmed by the effect it had on me.  I felt able to sleep much more deeply than
        I had in ages.  It affected me so much that I hatched a plan.  I started studying and
        practicing after I had my second baby, qualified with a Level 3 Diploma in Reflexology
        from Brighton Holistics and became a member of the Federation of Holistic Therapists and
        Association of Reflexologists. I have also become a member of the Complementary &amp;
        Natural Healthcare Council (CNHC) which means that if you have a private healthcare plan,
        you should be able to claim for the cost of the treatment.</p>
      <p>I live in Horsham with my two young boys and fur baby. These guys have taught me the importance of self-care - you can’t pour from an empty cup!  I am married to an Aussie, and we are normally planning our next big (or little) trip.  I love a festival, beach, music, yoga and running. Being in nature makes me happy.</p>
      <p style="margin-top: 50px; text-align: center;">
        <div class="image em-sig"></div>
      </p>
    </div>
    <div class="images">
      <div class="image"></div>
      <div class="image"></div>
    </div>
    <div class="image"></div>
  </div>
</template>

<script>
export default {
  data () {
    return {}
  }
}
</script>

<style scoped lang="less">
</style>
