// src/app/contact/contact.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: '.contact.content',
  templateUrl: './contact.component.html',
  styleUrls: ['./contact.component.less']
})
export class ContactComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<p>To make a booking, an enquiry, or just to find out a bit more about reflexology, please feel free to get in touch by any of the methods below:</p>
<div>Landline: 01403 256259</div>
<div>Mobile: 07706 279102</div>
<div>Email: emily@glowreflexology.co.uk</div>
<div>Facebook: glow_reflexology</div>
<div>Instagram: glow_reflexology</div>
<p style="margin-top: 10px;">I am very interested in working at festivals or corporate wellness days etc., please don’t hesitate to get in touch for a chat.</p>

// src/views/contact.vue
<template>
  <div class="contact content">
    <div class="title">
      <h2>contact</h2>
    </div>
    <div class="details">
      <div><strong>Landline</strong><span class="pull-right"><a href="tel:01403256259">01403 256259</a></span></div>
      <div><strong>Mobile</strong><span class="pull-right"><a href="tel:07706279102">07706 279102</a></span></div>
      <div><strong>Email</strong><span class="pull-right"><a href="mailto:emily@glowreflexology.co.uk">emily@glowreflexology.co.uk</a></span></div>
      <div><strong>Facebook</strong><a class="pull-right" href="https://www.facebook.com/glowwithreflexology/">@glowwithreflexology</a></div>
      <div><strong>Instagram</strong><a class="pull-right" href="https://www.instagram.com/glowwithreflexology/">@glowwithreflexology</a></div>
    </div>
    <div class="body-copy">
      <p>To make a booking, an enquiry, or just to find out a bit more about reflexology, please feel free to get in touch by any of the methods above.</p>
      <p>I am very interested in working at <strong>festivals or corporate wellness days</strong> etc., please don’t hesitate to get in touch for a chat.</p>
    </div>
  </div>
</template>

<script>
export default {
  data () {
    return {}
  }
}
</script>

<style></style>
