// src/app/data-protection-policy/data-protection-policy.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: '.data-protection-policy.content',
  templateUrl: './data-protection-policy.component.html',
  styleUrls: ['./data-protection-policy.component.less']
})
export class DataProtectionPolicyComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="title">
  <h3>General Data Protection Regulation (GDPR)</h3>
</div>
<div class="body-copy">
  <p>GDPR (implemented by DPA2018 in the UK) brought in new legal protection for personal information from May 2018. This tells you what personal information I hold and why, and what your rights are.</p>
  <p><strong>Therapist's Name / Identity:</strong> Emily Bryan / glow reflexology</p>
  <p><strong>Therapist's Contact Details:</strong></p>
  <ul style="list-style: none; margin-bottom: 25px;">
    <li><span style="text-decoration: underline;">Telephone</span> - 07706 279102</li>
    <li><span style="text-decoration: underline;">Email</span> - emily@glowreflexology.co.uk</li>
    <li><span style="text-decoration: underline;">Address</span> - 59 Blenheim Road, Horsham, RH12 5AQ</li>
  </ul>
  <p><strong>Data Controller Contact Details:</strong> same as above</p>
  <p><strong>Data Protection Officer:</strong> same as above</p>
  <h4>The Purpose of processing Client Data</h4>
  <p>In order to give professional reflexology treatments, I will need to gather and retain potentially sensitive information about your health. I will only use this information for informing reflexology treatments and associated recommendations concerning aspects of health and wellbeing which I will offer to you.</p>
  <h4>Lawful Basis for holding and using Client Information</h4>
  <p>As a full member of the Association of Reflexologists, I abide by the AoR Code of Practice and Ethics. The lawful basis under which I hold and use your information is my legitimate interests i.e. my requirement to retain the information in order to provide you with the best possible treatment options and advice.</p>
  <p>As I hold special category data (i.e. health related information), the Additional Condition under which I hold and use this information is: for me to fulfil my role as a health care practitioner bound under the AoR Confidentiality as defined in the AoR Code of Practice and Ethics.</p>
  <h4>What information I hold and what I do with it</h4>
  <p>In order to give professional reflexology treatments, I will need to ask for and keep information about your health. I will only use this for informing reflexology treatments and any advice I give as a result of your treatment. The information to be held is:</p>
  <ul style="margin-bottom: 20px;">
    <li>Your contact details</li>
    <li>Medical history and other health-related information (which I will take from you at first consultation)</li>
    <li>Treatment details and related notes (which I will take after each consultation)</li>
  </ul>
  <p>I will NOT share your information with anyone else (other than within my own practice, or as required for legal process) without explaining why it is necessary, and getting your explicit consent.</p>
  <h4>How Long I Retain Your Information for</h4>
  <p>I will keep your information for 8 years or for children,  records to be kept until the child is 25 or if 17 when treated, then 26.</p>
  <p>Your data will not be transferred outside the EU without your consent.</p>
  <h4>Protecting Your Personal Data</h4>
  <p>I am committed to ensuring that your personal data is secure. In order to prevent unauthorised access or disclosure, I have put in place appropriate technical, physical and managerial procedures to safeguard and secure the information we collect from you.</p>
  <p>I will contact you using the contact preferences you give me in relation to:</p>
  <ul style="margin-bottom: 20px;">
    <li>Appointment times</li>
    <li>Reflexology information or information related to your health</li>
    <li>Special offers and promotions (you may unsubscribe from this at any time)</li>
  </ul>
  <h4>Your Rights</h4>
  <p>GDPR gives you the following rights:</p>
  <ul style="margin-bottom: 20px;">
    <li>The right to be informed:<br /><em>To know how your information will be held and used (this notice).</em></li>
    <li>The right of access:<br /><em>To see your therapist’s records of your personal information, so you know what is held about you and can verify it.</em></li>
    <li>The right to rectification:<br /><em>To tell your therapist to make changes to your personal information if it is incorrect or incomplete.</em></li>
    <li>The right to erasure (also called “the right to be forgotten”):<br /><em>For you to request your therapist to erase any information they hold about you.</em></li>
    <li>The right to restrict processing of personal data:<br /><em>You have the right to request limits on how your therapist uses your personal information.</em></li>
    <li>The right to data portability:<br /><em>Under certain circumstances you can request a copy of personal information held electronically so you can reuse it in other systems.</em></li>
    <li>The right to object:<br /><em>To be able to tell your therapist you don’t want them to use certain parts of your information, or only to use it for certain purposes.</em></li>
    <li>Rights in relation to automated decision-making and profiling.</li>
    <li>The right to lodge a complaint with the Information Commissioner’s Office:<br /><em>To be able to complain to the ICO if you feel your details are not correct, if they are not being used in a way that you have given permission for, or if they are being stored when they don’t have to be.</em></li>
  </ul>
  <p>Full details of your rights can be found at <a href="https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr/individual-rights/" target="_blank">https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr/individual-rights/</a>.</p>
  <p>If you wish to exercise any of these rights, please use the contact details given above.</p>
  <p>If you are dissatisfied with the response you can complain to the Information Commissioner's Office; their contact details are at: <a href="https://www.ico.org.uk" target="_blank">www.ico.org.uk</a></p>
  <h4>Therapist's Rights</h4>
  <p>Please note:</p>
  <ul style="margin-bottom: 20px;">
    <li>If you don't agree to your therapist keeping records of information about you and your treatments, or if you don’t allow them to use the information in the way they need to for treatments, the therapist may not be able to treat you</li>
    <li>Your therapist has to keep your records of treatment for a certain period as described above, which may mean that even if you ask them to erase any details about you, they might have to keep these details until after that period has passed</li>
    <li>Your therapist can move their records between their computers and IT systems, as long as your details are protected from being seen by others without your permission.</li>
  </ul>
</div>

// src/views/data-protection-policy.vue
<template>
  <div class="data-protection-policy content">
    <div class="title">
      <h3>General Data Protection Regulation (GDPR)</h3>
    </div>
    <div class="body-copy">
      <p>GDPR (implemented by DPA2018 in the UK) brought in new legal protection for personal information from May 2018. This tells you what personal information I hold and why, and what your rights are.</p>
      <p><strong>Therapist's Name / Identity:</strong> Emily Bryan / glow reflexology</p>
      <p><strong>Therapist's Contact Details:</strong></p>
      <ul style="list-style: none; margin-bottom: 25px;">
        <li><span style="text-decoration: underline;">Telephone</span> - 07706 279102</li>
        <li><span style="text-decoration: underline;">Email</span> - emily@glowreflexology.co.uk</li>
        <li><span style="text-decoration: underline;">Address</span> - 59 Blenheim Road, Horsham, RH12 5AQ</li>
      </ul>
      <p><strong>Data Controller Contact Details:</strong> same as above</p>
      <p><strong>Data Protection Officer:</strong> same as above</p>
      <h4>The Purpose of processing Client Data</h4>
      <p>In order to give professional reflexology treatments, I will need to gather and retain potentially sensitive information about your health. I will only use this information for informing reflexology treatments and associated recommendations concerning aspects of health and wellbeing which I will offer to you.</p>
      <h4>Lawful Basis for holding and using Client Information</h4>
      <p>As a full member of the Association of Reflexologists, I abide by the AoR Code of Practice and Ethics. The lawful basis under which I hold and use your information is my legitimate interests i.e. my requirement to retain the information in order to provide you with the best possible treatment options and advice.</p>
      <p>As I hold special category data (i.e. health related information), the Additional Condition under which I hold and use this information is: for me to fulfil my role as a health care practitioner bound under the AoR Confidentiality as defined in the AoR Code of Practice and Ethics.</p>
      <h4>What information I hold and what I do with it</h4>
      <p>In order to give professional reflexology treatments, I will need to ask for and keep information about your health. I will only use this for informing reflexology treatments and any advice I give as a result of your treatment. The information to be held is:</p>
      <ul style="margin-bottom: 20px;">
        <li>Your contact details</li>
        <li>Medical history and other health-related information (which I will take from you at first consultation)</li>
        <li>Treatment details and related notes (which I will take after each consultation)</li>
      </ul>
      <p>I will NOT share your information with anyone else (other than within my own practice, or as required for legal process) without explaining why it is necessary, and getting your explicit consent.</p>
      <h4>How Long I Retain Your Information for</h4>
      <p>I will keep your information for 8 years or for children,  records to be kept until the child is 25 or if 17 when treated, then 26.</p>
      <p>Your data will not be transferred outside the EU without your consent.</p>
      <h4>Protecting Your Personal Data</h4>
      <p>I am committed to ensuring that your personal data is secure. In order to prevent unauthorised access or disclosure, I have put in place appropriate technical, physical and managerial procedures to safeguard and secure the information we collect from you.</p>
      <p>I will contact you using the contact preferences you give me in relation to:</p>
      <ul style="margin-bottom: 20px;">
        <li>Appointment times</li>
        <li>Reflexology information or information related to your health</li>
        <li>Special offers and promotions (you may unsubscribe from this at any time)</li>
      </ul>
      <h4>Your Rights</h4>
      <p>GDPR gives you the following rights:</p>
      <ul style="margin-bottom: 20px;">
        <li>The right to be informed:<br /><em>To know how your information will be held and used (this notice).</em></li>
        <li>The right of access:<br /><em>To see your therapist’s records of your personal information, so you know what is held about you and can verify it.</em></li>
        <li>The right to rectification:<br /><em>To tell your therapist to make changes to your personal information if it is incorrect or incomplete.</em></li>
        <li>The right to erasure (also called “the right to be forgotten”):<br /><em>For you to request your therapist to erase any information they hold about you.</em></li>
        <li>The right to restrict processing of personal data:<br /><em>You have the right to request limits on how your therapist uses your personal information.</em></li>
        <li>The right to data portability:<br /><em>Under certain circumstances you can request a copy of personal information held electronically so you can reuse it in other systems.</em></li>
        <li>The right to object:<br /><em>To be able to tell your therapist you don’t want them to use certain parts of your information, or only to use it for certain purposes.</em></li>
        <li>Rights in relation to automated decision-making and profiling.</li>
        <li>The right to lodge a complaint with the Information Commissioner’s Office:<br /><em>To be able to complain to the ICO if you feel your details are not correct, if they are not being used in a way that you have given permission for, or if they are being stored when they don’t have to be.</em></li>
      </ul>
      <p>Full details of your rights can be found at <a href="https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr/individual-rights/" target="_blank">https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr/individual-rights/</a>.</p>
      <p>If you wish to exercise any of these rights, please use the contact details given above.</p>
      <p>If you are dissatisfied with the response you can complain to the Information Commissioner's Office; their contact details are at: <a href="https://www.ico.org.uk" target="_blank">www.ico.org.uk</a></p>
      <h4>Therapist's Rights</h4>
      <p>Please note:</p>
      <ul style="margin-bottom: 20px;">
        <li>If you don't agree to your therapist keeping records of information about you and your treatments, or if you don’t allow them to use the information in the way they need to for treatments, the therapist may not be able to treat you</li>
        <li>Your therapist has to keep your records of treatment for a certain period as described above, which may mean that even if you ask them to erase any details about you, they might have to keep these details until after that period has passed</li>
        <li>Your therapist can move their records between their computers and IT systems, as long as your details are protected from being seen by others without your permission.</li>
      </ul>
    </div>
  </div>
</template>

<script>
export default {
  data () {
    return {}
  }
}
</script>

<style></style>
