// src/app/maternity/maternity.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: '.maternity.content',
  templateUrl: './maternity.component.html',
  styleUrls: ['./maternity.component.less']
})
export class MaternityComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="title">
  <h2>maternity reflexology</h2>
</div>
<h3>Maternity reflexology is an area of reflexology aimed specifically at couples during <strong>pre-conception, pregnancy and postnatal</strong> periods. Reflexology can be hugely benefitial at these times - research has shown that women who have regular reflexology treatments during pregnancy can shorten the duration of labour, and those having regular treatments may require less pain-relief during the course of delivery*.</h3>
<div class="image"></div>
<div class="box">
  <div>
    <p>*A research study showed reflexology in pregnancy significantly reduced pain during labour and reduced the length of the first stage (Valiani M et al - 2010 “Reviewing the effect of Reflexology on pain and outcomes of the labour of primiparous women” Iranian Journal of Nursing and Midwifery Research. 15 (Dec) p302-310)</p>
    <p>An earlier study showed first-time mums who received 10 reflexology treatments prior to birth had average labour times of five to six hours.  It was noted the group treated with reflexology needed far less pain relief during labour too.  (G. Motha and J. McGrath - 1992 “The effects of reflexology on labour outcome”)</p>
  </div>
</div>
<div class="body-copy">
  <h4>Pre-conception</h4>
  <p>Let reflexology help you get your body and mind to your optimal state for conception.</p>
  <p>Trying for a baby can be stressful, and it’s a time when it’s more important than ever to relax so that your body can fight off infection and ill health and you can maximise your chances of conception.</p>
  <p>Your reflexology sessions will last up to 1.5 hours (including consultation) and include lifestyle advice to help promote optimum body ecology for conception.</p>
  <p>Please get in touch to discuss a treatment plan tailored specifically to you.</p>
  <h4>Pregnancy</h4>
  <h5>1-15 weeks</h5>
  <p>While reflexology can do no harm, it is best to let nature take its course and reflexologists tend not to treat during this time.</p>
  <h5>16-36 weeks</h5>
  <p>A lovely relaxing treatment is recommended, with a focus on helping to ease any pregnancy aches and pains such as acidity, digestive issues, heartburn, constipation, hip and back pain, sciatica, bleeding gums, insomnia and many more. Treatments last roughly an hour (including consultation).</p>
  <h5>37 weeks+</h5>
  <p>At this point we add to the above treatment with techniques to help prime you for a natural labour. Treatments last up to 1.5 hours (including consultation).</p>
  <h4>Postnatal</h4>
  <p>Reflexology is a lovely treat in the weeks following birth, and can encourage hormonal rebalance, relax you and therefore increase the production of breast milk, boost the immune system, lift your mood and regulate your sleep patterns.  Treatments last roughly an hour (including consultation) and it is fine to have your new baby with you if that’s what you need.</p>
</div>

// src/views/maternity.vue
<template>
  <div class="maternity content">
    <div class="title">
      <h1>maternity reflexology</h1>
    </div>
    <h3>Maternity reflexology is an area of reflexology aimed specifically at couples during <strong>pre-conception, pregnancy and postnatal</strong> periods. Reflexology can be hugely benefitial at these times - research has shown that women who have regular reflexology treatments during pregnancy can shorten the duration of labour, and those having regular treatments may require less pain-relief during the course of delivery*.</h3>
    <div class="image"></div>
    <div class="box">
      <div>
        <p>*A research study showed reflexology in pregnancy significantly reduced pain during labour and reduced the length of the first stage (Valiani M et al - 2010 “Reviewing the effect of Reflexology on pain and outcomes of the labour of primiparous women” Iranian Journal of Nursing and Midwifery Research. 15 (Dec) p302-310)</p>
        <p>An earlier study showed first-time mums who received 10 reflexology treatments prior to birth had average labour times of five to six hours.  It was noted the group treated with reflexology needed far less pain relief during labour too.  (G. Motha and J. McGrath - 1992 “The effects of reflexology on labour outcome”)</p>
      </div>
    </div>
    <div class="body-copy">
      <h4>Pre-conception</h4>
      <p>Let reflexology help you get your body and mind to your optimal state for conception.</p>
      <p>Trying for a baby can be stressful, and it’s a time when it’s more important than ever to relax so that your body can fight off infection and ill health and you can maximise your chances of conception.</p>
      <p>Your reflexology sessions will last up to 1.5 hours (including consultation) and include lifestyle advice to help promote optimum body ecology for conception.</p>
      <p>Please get in touch to discuss a treatment plan tailored specifically to you.</p>
      <h4>Pregnancy</h4>
      <h5>1-15 weeks</h5>
      <p>While reflexology can do no harm, it is best to let nature take its course and reflexologists tend not to treat during this time.</p>
      <h5>16-36 weeks</h5>
      <p>A lovely relaxing treatment is recommended, with a focus on helping to ease any pregnancy aches and pains such as acidity, digestive issues, heartburn, constipation, hip and back pain, sciatica, bleeding gums, insomnia and many more. Treatments last roughly an hour (including consultation).</p>
      <h5>37 weeks+</h5>
      <p>At this point we add to the above treatment with techniques to help prime you for a natural labour. Treatments last up to 1.5 hours (including consultation).</p>
      <h4>Postnatal</h4>
      <p>Reflexology is a lovely treat in the weeks following birth, and can encourage hormonal rebalance, relax you and therefore increase the production of breast milk, boost the immune system, lift your mood and regulate your sleep patterns.  Treatments last roughly an hour (including consultation) and it is fine to have your new baby with you if that’s what you need.</p>
    </div>
  </div>
</template>

<script>
export default {
  data () {
    return {}
  }
}
</script>

<style></style>
