// src/app/pricing-offers/pricing-offers.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: '.pricing-offers.content',
  templateUrl: './pricing-offers.component.html',
  styleUrls: ['./pricing-offers.component.less']
})
export class PricingOffersComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<p>Foot reflexology treatment, based on a home visit - £35</p>
<h3>Special offers</h3>
<p>April & May “Introductory Offer”: £5 off a treatment</p>
<p>April & May “Recommend a friend”: if you are an existing client and you put a friend or family member in touch, both you and your friend can enjoy a treatment for £25
Loyalty scheme: enjoy your 6th treatment for free</p>
<h3>Cancellations</h3>
<p>While it is appreciated that emergencies can crop up at any time, glow reflexology is a small business so have to reserve the right to charge for the appointment if it is cancelled with less than 24 hours notice.</p>

// src/views/pricing-offers.vue
<template>
  <div class="pricing-offers content">
    <div class="title">
      <h2>pricing &amp; offers</h2>
    </div>
    <div class="body-copy">
      <h3>Home visit in Horsham and surrounding areas.</h3>
      <p>Foot reflexology treatment - <span class="bold">£35</span></p>
      <h3>Well & Good Studios</h3>
      <p>Foot reflexology treatment - <span class="bold">£45</span></p>
      <h3>Special offers</h3>
      <p><span class="bold">“Recommend a friend”:</span><br />If you are an existing client and you put a friend or family member in touch, both you and your friend can enjoy £10 off a treatment.</p>
      <p><span class="bold">Loyalty scheme:</span><br />Enjoy your 6th treatment for free</p>
      <h3>Cancellations</h3>
      <p>While it is appreciated that emergencies can crop up at any time, glow reflexology is a small business so have to reserve the right to charge for the appointment if it is cancelled with less than 24 hours notice.</p>
    </div>
    <div class="image"></div>
  </div>
</template>

<script>
export default {
  data () {
    return {}
  }
}
</script>

<style></style>
