// src/app/what-to-expect/what-to-expect.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: '.what-to-expect.content',
  templateUrl: './what-to-expect.component.html',
  styleUrls: ['./what-to-expect.component.less']
})
export class WhatToExpectComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="title">
  <h2>what to expect</h2>
</div>
<h3>I operate both on a mobile basis within a 10 mile radius of Horsham and every other Saturday at Well &amp; Good Studios in Godalming. </h3>
<div class="image"></div>
<div class="body-copy">
  <p><strong>Relax in the comfort of your own home - Horsham and surrounding areas.</strong></p>
  <p>Evening and Saturday morning appointments are available.  Everything required is provided (chair, towels, music etc.). We just need a quiet space so that you can really relax.</p>
  <p><strong>Enjoy the laid back vibe of a super cool new health & wellness studio - Well & Good Studios, 65b High Street, Godalming, GU7 1AW</strong></p>
  <p>Please check my social media or get in touch for an up to date list of dates and times available, but normally it will be every other Saturday morning.
  <p>Clients are encouraged to wear comfy clothes during a treatment to enable maximum relaxation (pyjamas are totally fine!) A choice of scented massage wax and music is available as everyone relaxes differently. An optional warming scented eye mask or weighted blanket are on hand to maximise relaxation.</p>
  <p>The session starts with a consultation which helps me to understand any past or current health or lifestyle issues so that the treatment can be tailored to you, to ensure you get the most out of the session.</p>
  <p>You only need to remove your socks and shoes, and wear trousers that are able to be rolled up a bit with ease.</p>
  <p>I start with a warm up massage then undertake a full treatment which involves a range of different pressure techniques on your feet and lower legs with a level of pressure that suits you. I then finish with a warm down massage.  During this time feel free to completely zone out, fall asleep - snoring is a good sign that it is working!</p>
  <p><strong>The treatment + consultation lasts approximately 1 hour.</strong></p>
</div>

// src/views/what-to-expect.vue
<template>
  <div class="what-to-expect content">
    <div class="title">
      <h2>what to expect</h2>
    </div>
    <h3>I operate both on a mobile basis within a 10 mile radius of Horsham and every other Saturday at Well &amp; Good Studios in Godalming. </h3>
    <div class="image"></div>
    <div class="body-copy">
      <p><strong>Relax in the comfort of your own home - Horsham and surrounding areas.</strong></p>
      <p>Evening and Saturday morning appointments are available.  Everything required is provided (chair, towels, music etc.). We just need a quiet space so that you can really relax.</p>
      <p><strong>Enjoy the laid back vibe of a super cool new health & wellness studio - Well & Good Studios, 65b High Street, Godalming, GU7 1AW</strong></p>
      <p>Please check my social media or get in touch for an up to date list of dates and times available, but normally it will be every other Saturday morning.
      <p>Clients are encouraged to wear comfy clothes during a treatment to enable maximum relaxation (pyjamas are totally fine!) A choice of scented massage wax and music is available as everyone relaxes differently. An optional warming scented eye mask or weighted blanket are on hand to maximise relaxation.</p>
      <p>The session starts with a consultation which helps me to understand any past or current health or lifestyle issues so that the treatment can be tailored to you, to ensure you get the most out of the session.</p>
      <p>You only need to remove your socks and shoes, and wear trousers that are able to be rolled up a bit with ease.</p>
      <p>I start with a warm up massage then undertake a full treatment which involves a range of different pressure techniques on your feet and lower legs with a level of pressure that suits you. I then finish with a warm down massage.  During this time feel free to completely zone out, fall asleep - snoring is a good sign that it is working!</p>
      <p><strong>The treatment + consultation lasts approximately 1 hour.</strong></p>
    </div>
  </div>
</template>

<script>
export default {
  data () {
    return {}
  }
}
</script>

<style></style>
